language: node_js
cache: yarn

before_script:
  - yarn install

script:
  - yarn run build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master